version: '3.9'

services:
  service:
    build:
      context: .
      dockerfile: resources/docker/service/Dockerfile
    volumes:
      - ./service:/app
    env_file: $PWD/service/.env
    command: go run .
    ports:
      - 8888:8888
    networks:
      - internal
    
  ui:
    build:
      context: .
      dockerfile: resources/docker/ui/Dockerfile
    volumes:
      - ./ui:/frontend
    env_file: $PWD/ui/.env
    command: npm run dev
    ports:
      - 3000:3000
    networks:
      - internal

  npm:
    build:
      context: .
      dockerfile: resources/docker/ui/Dockerfile
    entrypoint: [ "npm" ]
    working_dir: /frontend
    command: [ "-v" ]
    volumes:
      - ./ui:/app

  go:
    build:
      context: .
      dockerfile: resources/docker/service/Dockerfile
    entrypoint: [ "go" ]
    working_dir: /app
    command: [ "-v" ]
    volumes:
      - ./service:/app

networks:
  internal:
    driver: bridge