version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: resources/docker/api/Dockerfile
    volumes:
      - ./api:/app
    env_file: $PWD/api/.env
    command: go run .
    ports:
      - 8888:8888
    
  ui:
    build:
      context: .
      dockerfile: resources/docker/ui/Dockerfile
    volumes:
      - ./ui:/app
    env_file: $PWD/ui/.env
    command: npm run dev
    ports:
      - 80:3000