name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push UI
        uses: docker/build-push-action@v5
        with:
          context: .
          file: resources/docker/ui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lanops-spotify-jukebox-ui:latest
      -
        name: Build and push API
        uses: docker/build-push-action@v5
        with:
          context: .
          file: resources/docker/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lanops-spotify-jukebox-api:latest
